# Generated by Django 4.1.5 on 2023-01-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('preferr_number', models.IntegerField(null=True)),
                ('preferr_color', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
