# Generated by Django 4.1.5 on 2023-01-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_mgmt_app', '0002_client_group_member_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('preferr_number', models.IntegerField(null=True)),
                ('preferr_color', models.CharField(max_length=10, null=True)),
                ('group_id', models.CharField(max_length=1, null=True)),
            ],
        ),
    ]
